"""Render per-harness SKILL.md wrappers from a canonical spec."""

from __future__ import annotations

import re
import shlex
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

from .schema import CanonicalSpec, Invocation

HARNESSES = ("hermes", "openclaw", "claude_code")
_TEMPLATES = Path(__file__).parent / "templates"
_WS = re.compile(r"\s+")
_DEFAULT_CATEGORY = "general"


def _oneline(text: str) -> str:
    """Collapse internal whitespace/newlines to single spaces and strip ends."""
    return _WS.sub(" ", text).strip()


def _category(spec: CanonicalSpec) -> str:
    """The Hermes category for ``spec`` (from ``harnesses.hermes.category``)."""
    return str(spec.harnesses.get("hermes", {}).get("category", _DEFAULT_CATEGORY))


def skill_root(harness: str, spec: CanonicalSpec) -> str:
    """Return the deployed skill-root path for ``spec`` under ``harness``.

    This is the value substituted for the ``{skill_root}`` token in a cli
    invoke's ``exec`` command.

    Args:
        harness: one of :data:`HARNESSES`.
        spec: the canonical spec (supplies name and Hermes category).

    Returns:
        The harness-correct skill-root path.

    Raises:
        ValueError: if ``harness`` is unknown.
    """
    if harness == "hermes":
        return f"~/.hermes/skills/{_category(spec)}/{spec.name}"
    if harness == "openclaw":
        return f"/home/node/.openclaw/workspace/skills/{spec.name}"
    if harness == "claude_code":
        return f"~/.claude/skills/{spec.name}"
    raise ValueError(f"unknown harness: {harness!r} (expected one of {HARNESSES})")


def build_context(spec: CanonicalSpec, harness: str) -> dict[str, Any]:
    """Flatten a spec into the plain dict the ``harness`` template consumes.

    Args:
        spec: the canonical spec.
        harness: one of :data:`HARNESSES` (selects the ``{skill_root}`` value).

    Returns:
        A dict with ``mcp_servers`` (structured list), ``cli_cmds`` (exec
        strings with ``{skill_root}`` resolved), and the shared metadata fields.
    """
    root = skill_root(harness, spec)
    required_env: list[str] = []
    mcp_servers: list[dict[str, Any]] = []
    cli_cmds: list[str] = []
    for inv in spec.invokes:
        for e in inv.required_env:
            if e not in required_env:
                required_env.append(e)
        if inv.kind == "mcp":
            mcp_servers.append(
                {
                    "server": inv.server,
                    "transport": inv.transport,
                    "tools": list(inv.tools),
                    "required_env": list(inv.required_env),
                }
            )
        elif inv.kind == "cli" and inv.exec is not None:
            cli_cmds.append(inv.exec.replace("{skill_root}", root))
    return {
        "name": spec.name,
        "description": _oneline(spec.description),
        "version": spec.version,
        "triggers": list(spec.triggers),
        "category": _category(spec),
        "mcp_servers": mcp_servers,
        "cli_cmds": cli_cmds,
        "required_env": required_env,
        "usage": _oneline(spec.usage) if spec.usage else None,
        "guardrails": [{"id": g.id, "text": _oneline(g.text)} for g in spec.guardrails],
        "model_tier": spec.model_tier,
    }


def _env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(_TEMPLATES)),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )


_REGISTRATION_HEADER = (
    "# Generated by trapezia-skill-gen - merge into the Hermes config.yaml `mcp_servers` mapping.\n"
    "# Operator: point `command` at the skill's isolated venv interpreter if one is used,\n"
    "# and adjust `cwd` to that venv/checkout as needed (Phase 0 F-6).\n"
)


def _registration_block(inv: Invocation, spec: CanonicalSpec) -> dict[str, Any]:
    """Build one `mcp_servers.<name>` stdio block from an mcp invoke."""
    argv = shlex.split(inv.launch) if inv.launch else []
    command = argv[0] if argv else "python"
    args = argv[1:] if len(argv) > 1 else []
    block: dict[str, Any] = {"command": command, "args": args}
    if inv.required_env:
        block["env"] = {e: f"${{{e}}}" for e in inv.required_env}
    block["cwd"] = skill_root("hermes", spec)
    return block


def generate_mcp_registration(spec: CanonicalSpec) -> str | None:
    """Render the Hermes `mcp_servers` registration snippet for ``spec``.

    Emits one stdio ``mcp_servers.<server>`` block per mcp invoke (command/args
    from ``launch``, env from ``required_env`` as ``${VAR}`` references, cwd at
    the Hermes skill root). The block is a merge fragment the operator applies to
    ``config.yaml`` (Chris's decision: committed snippet, manual merge).

    Args:
        spec: the canonical spec.

    Returns:
        The YAML snippet, or ``None`` if the spec declares no mcp invoke.
    """
    servers = {
        inv.server: _registration_block(inv, spec)
        for inv in spec.invokes
        if inv.kind == "mcp"
    }
    if not servers:
        return None
    body: str = yaml.safe_dump({"mcp_servers": servers}, sort_keys=False, default_flow_style=False)
    return _REGISTRATION_HEADER + body


def generate(spec: CanonicalSpec, harness: str) -> str:
    """Render the SKILL.md text for ``harness`` from ``spec``.

    Args:
        spec: the canonical spec.
        harness: one of :data:`HARNESSES`.

    Returns:
        The rendered SKILL.md content.

    Raises:
        ValueError: if ``harness`` is unknown.
    """
    if harness not in HARNESSES:
        raise ValueError(f"unknown harness: {harness!r} (expected one of {HARNESSES})")
    template = _env().get_template(f"{harness}.md.j2")
    return template.render(**build_context(spec, harness))
